name: growwise_mobile_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true

  
  assets:
  - assets/images/growwise_logo.png
  - assets/images/onboarding1.png
  - assets/images/onboarding2.png
  - assets/images/auth-img.png
 
  - assets/icons/crop.png
  - assets/icons/care.png
  - assets/icons/disease.png
  - assets/icons/google.png