// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9-mgyMfSlhuogBLiWD2ceScUzZ6Mo0hk',
    appId: '1:982637480206:web:aa49248551109d1f8a6f5f',
    messagingSenderId: '982637480206',
    projectId: 'growwise-app-9478f',
    authDomain: 'growwise-app-9478f.firebaseapp.com',
    storageBucket: 'growwise-app-9478f.firebasestorage.app',
    measurementId: 'G-V4W7L41G7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFTrz9xb7Yxd5EO9KRBgbwRR9rGbRee78',
    appId: '1:982637480206:android:9af2f3ee623f99ff8a6f5f',
    messagingSenderId: '982637480206',
    projectId: 'growwise-app-9478f',
    storageBucket: 'growwise-app-9478f.firebasestorage.app',
  );
}
